
version: '2'
services:
  mariadb:
    image: mariadb:latest
    environment:
      #- ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=bitnami_moodle
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_USER=bn_moodle
      - MYSQL_PASSWORD=123456
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./data/mariadb_data:/var/lib/mysql:Z
      
  moodle:
    image: docker.io/bitnami/moodle:3-debian-10
    ports:
      - 8080:8080
      - 443:8443
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_DATABASE_PASSWORD=123456
        # MOODLE SETTINGS
      - MOODLE_USERNAME=user
      - MOODLE_PASSWORD=bitnami
      - MOODLE_EMAIL=user@example.com
      - MOODLE_SITE_NAME='New Site'
      #- ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./data/moodle_data:/bitnami/moodle:Z
      - ./data/moodledata_data:/bitnami/moodledata:Z
    depends_on:
      - mariadb