version: '3.3'

services:
   db:
     image: mariadb:latest
     volumes:
       - ./data/db:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: admin
       MYSQL_DATABASE: admin
       MYSQL_USER: admin
       MYSQL_PASSWORD: admin

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - 8000:80
     volumes:
       - ./data/html:/var/www/html
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: admin
       WORDPRESS_DB_PASSWORD: admin
       WORDPRESS_DB_NAME: admin
   
   phpmyadmin:
     depends_on:
       - db
     image: phpmyadmin/phpmyadmin
     restart: always
     ports:
       - 8001:80
     environment:
       PMA_HOST: db
       MYSQL_ROOT_PASSWORD: admin
       MYSQL_PASSWORD: admin

